### ISSUE TITLE
Files are missing in NuGet package of version 1.0.3.68

### ISSUE THREAD

**Issue by faubulous** [semiodesk/trinity-rdf#22]
When downloading the example from trinity-rdf.net on recent Windows versions there is no .NET Core 2.1 installed. However, when upgrading to .NET Core 3.1 the example fails to create resources in the DotNetRDF memory model. When switching to .NET Standard 2.0 the program crashes with the following exception:

```
Unhandled Exception: System.TypeInitializationException: The type initializer for 'TrinityExample.Program' threw an exception. ---> System.IO.FileNotFoundException: Could not load file or assembly 'Semiodesk.Trinity, Version=1.0.3.68, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified.
   at TrinityExample.Program..cctor()
   --- End of inner exception stack trace ---
   at TrinityExample.Program.Main()
```

The problem seems to be that the NuGet package of version 1.0.3.68 is missing the following folders:

- build
- tools

This explains why the ontology generator is not working and the CIL generator is not implementing constructors and property accessors.

**Comment by PhilKlae** [comment]
I can confirm that currently the First steps example from the homepage does not work due to the same reason

**Comment by PhilKlae** [comment]
@faubulous is there a way to manually fix this?
I am bound to use the latest version because of library dependencies in my project.

**Comment by faubulous** [comment]
@PhilKlae You could try to copy the `build` and `tools` folder [of an older version](https://nuget.info/packages/Semiodesk.Trinity/1.0.3.49) into the NuGet package folder in `{USER_FOLDER}/.nuget/semiodesk.trinity/{PACKAGE_VERSION}`.

Meanwhile @meberl has pushed a fix that we're currently testing and should be deployed soon.

**Comment by PhilKlae** [comment]
Big Thx @faubulous ! your workaround did the job, but I see 1.0.3.70 is live and has the missing folders included.

**Comment by faubulous** [comment]
You're welcome.

For the record: We saw some issues when people updated the project to 1.0.3.70 then Visual Studio would not properly update its internal caches and throw build errors. However, these are resolved when restarting Visual Studio after a package update.

I am closing this issue now.
