### ISSUE TITLE
Dependency on NetCore although I build for netstandard2.x

### ISSUE THREAD

**Issue by PhilKlae** [semiodesk/trinity-rdf#23]
**Hi :)** 

I am trying to use Trinity with Unity game engine 2021.3.5, it does not support netcore, it supports netstandard2.1 and net4.6. 
I am roughly following the instructions from the homepage and adjusted a few things. So basically I am building a dll with trinity and a datastore inside and access it in unity.

Sadly I get an error when using any function from the built dll:

> could not load file or assembly 'System.Private.CoreLib, Version=4.0.0.0

I get this error when targeting net4.6, netstandard2.1 and netstandard2.0 in the Trinity project.

Which seems to mean that the library needs netcore, am I understanding something wrong here? Sharing my .csproj file below.

[DataModelV2.zip](https://github.com/semiodesk/trinity-rdf/files/10096073/DataModelV2.zip)

(i cant get to xml in a readable format in here, theres nothing special inside, pasting a few interesting lines if you dont want to download the .zip)

-      <TargetFramework>netstandard2.1</TargetFramework>
-     <PackageReference Include="dotNetRDF" Version="2.7.5" />
-     <PackageReference Include="Semiodesk.Trinity" Version="1.0.3.70" />
-     <PackageReference Include="Newtonsoft.Json" Version="13" />

**Comment by faubulous** [comment]
Dear @PhilKlae 

we do not have any known dependencies on .NET Core and Trinity should be built for .NET Standard 2.0. We removed support for 4.x Framework a couple of months ago. Your error might be [related to this Unity issue](https://forum.unity.com/threads/what-is-system-private-corelib-dll-and-why-is-it-giving-me-an-error-on-uwp.514670/)

There might be special packaging restrictions for Unity applications that apply here. Older versions of Trinity used to work with Unity. But we are not actively testing this platform anymore, I'm afraid.

**Comment by PhilKlae** [comment]
Hi @faubulous 

Thanks for the quick reply and the reference!
I can imagine the usage of ontologies/rdf and Unity engine is quite nieche (although I think they fit together very well).

Sadly I did not get this to work, I will post a solution if I ever find one and close the issue for now.
