### ISSUE TITLE
I can only seem to connect to stardog on localhost

### ISSUE THREAD

**Issue by Chris-MorrisUK** [semiodesk/trinity-rdf#8]
When I use trinityRDF to connect to stardog running on localhost I can query it and all works well. When however I connect to a server on a remote machine (on the same network) I get an error:
 
>     A HTTP error occurred while beginning a Transaction in the Store. No response, see aforementioned status line or inner exception for further details
> 
Inner exception:
> 
>     A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond

I can connect to the remote instance of stardog using other libraries or stardog studio. If I stand up an instance of stardog on localhost and alter the connection string to match I can also connect to it. 

The dysfunctional connection string is:  `"provider=stardog;host=http://192.168.221.121:5820;uid=admin;pw=admin;sid=music";`
The working connection string is: `"provider=stardog;host=http://localhost:5820;uid=admin;pw=admin;sid=music"`

In order as to elminate as many sources of error as possible I've recreated this in the stardog  "TrinityConsoleSample" sample code from stardog. 

I've asked this on [stackoverflow ]( https://stackoverflow.com/questions/67937112/connecting-to-stardog-with-trinityrdf-exception-thrown-if-address-other-than-lo)too, but this might be a more appropriate place.

**Comment by meberl** [comment]
Which version of trinity-rdf did you use? We use dotnetrdf internally and updated to version 2.7 recently. Maybe there was an issue in there that got fixed.
You can also try to remove the call to `store.InitializeFromConfiguration()` and try to open a connection to Stardog by instantiating StardogStore directly with:
`
StardogStore(string host, string username, string password, string storeId)
`

**Comment by Chris-MorrisUK** [comment]
I was using version 1.0.3.30, though your comment caused me to try updating to 1.0.3.49 and sadly the issue has persisted. dotNetRDf  is on version 2.7.0 

Not calling `store.InitializeFromConfiguration()` and instead creating the store directly does prevent it crashing on that line, however I get the same exception when I try to access the Model, created by that store,:

`            IStore store = new StardogStore("http://192.168.221.121:5820", "admin", "admin", "music");
            watch.Stop();

            Console.WriteLine("Connecting to Stardog took: {0} ms", watch.ElapsedMilliseconds);

            // Uncomment the following line to write all SPARQL queries to
            // STDERR (useful for debugging)
             store.Log = (query) => Console.Error.WriteLine(query);

            // A model (named graph) is where we collect resources that logically belong together
            Model = store.GetModel(new Uri("http://stardog.com/tutorial"));

            #region using reasoning with LINQ

            watch.Restart();

            // NOTE: Creating a Queryable<> does not issue a query. Queries are created and executed in a
            // lazy fashion when you access the results, depending on your requested result type:
            //
            // Default: SPARQL SELECT
            // Count(): SPARQL SELECT COUNT(x)
            // Any(): SPARQL ASK
            var artistsWithReasoning = Model.AsQueryable<Artist>(true);

            Console.WriteLine($"With reasoning set to 'true', the artists query returned {artistsWithReasoning.Count()} records");`
            
            The exception is now thrown on the console.writeline. The comments were in the example, they're not mine.

**Comment by faubulous** [comment]
Maybe @DarthStem can help us here?

**Comment by faubulous** [comment]
Closing due to removed Stardog support from Trinity RDF 1.0.3.50
