### ISSUE TITLE
Get Model from Default graph

### ISSUE THREAD

**Issue by jiatao99** [semiodesk/trinity-rdf#9]
I followed the example code to hit my own StarDog server and stuck at the following line:

```
store.GetModel(new Uri(...));
```

Since all my data is saved under the default graph, what `Uri` should I passing in?

I believe the the URI will be translate to FROM statement. If I remove the from statement generated from log everything runs fine. 

Thanks

**Comment by meberl** [comment]
If you want to execute a query without a FROM clause, you can use 
`
store..ExecuteQuery(...)
`

When you query without a FROM clause, the behaviour can vary from vendor to vendor. Some execute the query on all graphs.

**Comment by faubulous** [comment]
Closing due to removed Stardog support from Trinity RDF 1.0.3.50
